"""
Decoder file for ML Models for the Fledge Federated Learning Framework. 
Currently, development work taking place only for encoding PyTorch models with protobuf, and sending
them over a network using gRPC. 
"""
# module imports
from collections import OrderedDict

# Imports for layer types.
from onnx_manager.onnx_manager import ONNXManager

class ProtoDecoder:
    """
    A decoder class, that takes in the generated byte-string from the Encoder's encode_model_layers function
    and returns a reconstructed model on the client side. 
    """
    def __init__(self, encoded_model: str) -> None:
        self.encoded_model = encoded_model
        self.manager = ONNXManager()
    
    def decode_model_layers(self) -> OrderedDict:
        """
        A function that decodes the encoded model byte-string, generated using protobuf.

        Returns:
            OrderedDict: Returns an ordered dictionary of the module layers involved within the model.
        """
        return self.manager.decode(self.encoded_model)


